docs/macros.md
Libraries have a couple of use cases where `Evals.eval` was used in compile-time:
1) [for expensive calculations of LUT tables that should happen in compile-time and produce resulting array of primitives](https://github.com/plokhotnyuk/jsoniter-scala/blob/acaded784e95b9c65fe431356ba315bd00aa8363/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L2390-L2414) (one possible solution provided below in comments, but it leads to code duplication between Scala 2 and Scala 3 codebases)
2) [for injecting user-defined pure functions that configure behavior during macro expansions, so should be instantiated and called in compile-time](https://github.com/plokhotnyuk/jsoniter-scala/blob/acaded784e95b9c65fe431356ba315bd00aa8363/jsoniter-scala-macros/src/main/ …
=> Add libraries that require replacement for `Evals.eval`

docs/dotty-rewrites.md
This PR contains:
- Usage of `-source:3.0-migration`, `-explain` and `-rewrite` in the context of migration
- Documentation and examples of the migration rewrite rules
For the reviewers, I would be interested in knowing if:
- the technical details are correct
- the example codes are meaningful, concise, and rather exhaustive at the same time
- the English wording is good enough
Also do you think it would be good to set up an sbt project that tests the regression in the documented rules? Is it redundant with the Dotty tests?
=> Document the Dotty rewrite rules for migration

.github/workflows/continuous-integration.yml, .gitignore, build.sbt, project/FileChecker.scala, project/build.properties, project/plugins.sbt, rewrites/src/check/scala-3.0/1-keywords.scala, rewrites/src/check/scala-3.0/2-lambdaParam.scala, rewrites/src/check/scala-3.0/3-symbolLitterals.scala, rewrites/src/check/scala-3.0/4-indentArgument.scala, rewrites/src/check/scala-3.0/5-doWhile.scala, rewrites/src/check/scala-3.0/6-procedure.scala, rewrites/src/check/scala-3.1/7-wildcard.scala, rewrites/src/input/scala-3.0/1-keywords.scala, rewrites/src/input/scala-3.0/2-lambdaParam.scala, rewrites/src/input/scala-3.0/3-symbolLitterals.scala, rewrites/src/input/scala-3.0/4-indentArgument.scala, rewrites/src/input/scala-3.0/5-doWhile.scala, rewrites/src/input/scala-3.0/6-procedure.scala, rewrites/src/input/scala-3.1/7-wildcard.scala
Add tests for the documented rewrite rules.
The `rewrites / test` task will perform these steps:
- copy the source files from `rewrites/input/`  to `rewrites/target/src-managed/`
- compile the files in `rewrites/target/src-managed/` with `-source:3.0-migration -rewrite`
- compare the files in `rewrites/target/src-managed/` with the files in `rewrites/check/`
It is also possible to change the migration version to 3.1 to test the `-source:3.1-migration` rules.
=> Add tests for rewrite rules

.github/workflows/continuous-integration.yml, .gitignore, build.sbt, incompat/type-infer-1/README.md, incompat/type-infer-1/src/main/scala-2.13/type-infer.scala, incompat/type-infer-1/src/main/scala/type-infer.scala, project/FileChecker.scala
This PR is the ground work for tracking the found incompatibilities and their evolutions.
Each incompatibility is described by a project under the `incompat/` directory. The `incompat` project is an aggregation of all incompatibility projects.
Each incompatibility contains:
- a short `README.md` that describes the incompatibility: origin, compiler message, related documentation, related issues...
- a `src/main/scala-2.13` source directory that must compile in Scala 2.13 but not in Dotty
- a proposed solution under `src/main/scala/` that must compile with Scala 2.13 and Dotty
Whatever is the scala version, the `compile` task will compile the `src/main/scala` source directories exclusively.
To compile the `src/main/scala-2.13` you must run `CompileBackward / compile` task.
The `test` task …
=> Add and test incompatibilities

.github/workflows/continuous-integration.yml, build.sbt, docs/dotty-rewrites.md, rewrites/src/check/scala-3.0/8-inherit-shadowing.scala, rewrites/src/check/scala-3.0/9-value-eta-expansion.scala, rewrites/src/check/scala-3.1-deprecation/3-alphanumeric-infix.scala, rewrites/src/check/scala-3.1/2-implicit-lambda-param.scala, rewrites/src/check/scala-3.1/4-pattern-binding.scala, rewrites/src/check/scala-3.1/5-eta-expansion.scala, rewrites/src/check/scala-3.1/6-context-bound-arg.scala, rewrites/src/input/scala-3.0/8-inherit-shadowing.scala, rewrites/src/input/scala-3.0/9-value-eta-expansion.scala, rewrites/src/input/scala-3.1-deprecation/3-alphanumeric-infix.scala, rewrites/src/input/scala-3.1/2-implicit-lambda-param.scala, rewrites/src/input/scala-3.1/4-pattern-binding.scala, rewrites/src/input/scala-3.1/5-eta-expansion.scala, rewrites/src/input/scala-3.1/6-context-bound-arg.scala
Document the previously missing `3.0-migration` and `3.1-migration` Dotty rewrite.
=> Complete the list of 3.0-migration and 3.1-migration rewrites

docs/incompatibility-table.md, website/i18n/en.json, website/sidebars.json, website/static/css/custom.css
The incompatibility table is the entrypoint for finding an incompatibility and learning about the solutions.
The incompatibilities are classified in 4 categories (Syntactic Changes, Dropped Features, Contextual Abstraction, Other Changed Features). The implicit resolution, type inference and macros incompatibilities are also mentionned.
Each tables give an overview of the incompatibilities based on:
- is there a warning in Scala 2.13
- is there a Dotty rewrite
- is there an existing Scalafix rule
The next step will be to link each incompatibility to its description, that is stored in the `/incompat` folder.
=> Add incompatibility table

docs/macros/status.md
Just to make things a tiny bit more visually scannable at a glance.
=> Alphabetize macro library migration status

.gitignore, README.md, docs/compatibility.md, docs/dotty-rewrites.md, docs/dotty-syntax-rewrites.md, docs/get-started.md, docs/incompatibilities/table.md, docs/macros/macros.md, docs/macros/status.md, incompat-3.0/README.md, incompat-3.0/auto-application/README.md, incompat-3.0/default-param-variance/README.md, incompat-3.0/do-while/README.md, incompat-3.0/early-initializer/README.md, incompat-3.0/implicit-view/README.md, incompat-3.0/indent-argument/README.md, incompat-3.0/inheritance-shadowing/README.md, incompat-3.0/keywords/README.md, incompat-3.0/lambda-params/README.md, incompat-3.0/procedure-syntax/README.md, incompat-3.0/symbol-literals/README.md, incompat-3.0/type-infer-10/README.md, incompat-3.0/type-of-implicit-def/README.md, incompat-3.0/value-eta-expansion/README.md, incompat-3.0/wildcard-argument/README.md
- Following the announcement that the upcoming change in the
naming of the Dotty atifacts to Scala [3], this name change
is applied to the migration guide by renaming Dotty to Scala 3
where applicable
- A minor update to .gitignore to ignore VCS artifacts
- Resolves #67
=> Rename dotty to Scala 3

.github/workflows/tests.yml, docs/compatibility.md, docs/tutorials/sbt-migration.md, sbt-migration-tutorial.sbt, sbt-migration-tutorial/src/main/scala/app/Main.scala, website/i18n/en.json, website/sidebars.json
First half of the tutorial for porting an sbt project (#61).
=> Add sbt Migration tutorial

docs/macros/macro-libraries.md
airframe-log is one of the modules of Airframe project https://wvlet.org/airframe. It's ported to Scala 3 macros https://github.com/wvlet/airframe/pull/1381
=> Add airframe-log to Scala 3 macro library list

incompat-30/auto-application/README.md
The terminology around 0-arity method is not used consistently, and not clear so we should use the term used in 'Programming in Scala', which is _empty-paren_ method.
If we insist on using the jargon, then _nilary_ is the term sometimes used in scala/scala discussions. See for instance https://contributors.scala-lang.org/t/nullary-and-nilary-methods/3756
|                  | Programming in Scala  | scala/scala jargon |
|------------------|-----------------------|--------------------|
| `def foo: Int`   | parameterless methods | nullary method     |
| `def foo(): Int` | empty-paren methods   | nilary method      |
[The great () insert](https://github.com/lampepfl/dotty/pull/2716) where this doc came from doesn't seem to use it this way, so like I said it's inconsistent and best to avoid it …
=> Fix "nullary method"

docs/incompatibilities/other-changed-features.md, docs/incompatibilities/table.md, incompat-30/case-class-companion/README.md, incompat-30/case-class-companion/src/main/scala-2.13/case-class-companion.scala, incompat-30/case-class-companion/src/main/scala/case-class-companion.scala, incompat.sbt
=> Add case-class-companion incompatibility

docs/scala-3-migration-mode.md
there is no `dotc` but `scalac` only
=> replace dotc with scalac

docs/macros/metaprogramming.md
According to https://github.com/lampepfl/scala3-macro-tutorial:
> The macro tutorial has been moved to [docs.scala-lang.org](https://docs.scala-lang.org/)
=> Fix macro tutorial links

docs/get-started.md, docs/tutorials/prerequisites.md, website/i18n/en.json, website/pages/en/index.js, website/sidebars.json, website/siteConfig.js
The Algolia search index has not been updated for quite some time now.
This is probably caused by an outdated link in the [Algolia config](https://github.com/algolia/docsearch-configs/blob/master/configs/scala-3-migration-guide.json)
This PR attempts to fix it by reviving the "https://scalacenter.github.io/scala-3-migration-guide/docs/get-started.html" url.
Related issue: #174
=> Try fix algolia

docs/incompatibilities/incompatibility-table.md, docs/incompatibilities/other-changed-features.md, incompat-30/infer-return-type/README.md, incompat-30/infer-return-type/src/main/scala-2.13/infer-return-type.scala, incompat-30/infer-return-type/src/main/scala/infer-return-type.scala, incompat.sbt, website/i18n/en.json
Fixes #181 
```scala
class Foo
class RichFoo(foo: Foo) extends Foo {
def show: String = ""
}
class Parent {
def foo: Foo = new Foo
}
class Child extends Parent {
override def foo = new RichFoo(super.foo)
}
object Test {
(new Child).foo.show // Scala 3 error: value show is not a member of Foo
}
```
@smarter Is the Scala 3 behavior intentional?
=> Add incompat: Inferred return type of an override method

docs/tooling/scala-3-syntax-rewrites.md
Small typo fixed: Missing closing '}'
=> Small typo fixed: Missing closing '}'

docs/compiler-options/compiler-options-table.md, docs/incompatibilities/other-changed-features.md, docs/tutorials/kind-projector.md
Document new features implemented in https://github.com/lampepfl/dotty/pull/12378 https://github.com/scala/scala/pull/9605 https://github.com/typelevel/kind-projector/pull/188
=> Document migration to Scala 3 Underscore Type Lambdas syntax and cross-compiling with kind-projector

website/i18n/en.json, website/sidebars.json
@adpi2 Sorry, I forgot to add the page to sidebar so currently it's only accessible by URL. this fixes that
=> Add kind-projector Migration Tutorial to sidebar index

docs/tutorials/kind-projector.md
@adpi2 Turns out there were a few more minor errors still. Sorry!
=> kind-projector.md: Fix wrong scala version and missing code block

docs/macros/macro-libraries.md
Shapeless and Magnolia received a new home (organization) and made progress in their Scala 3 migration
=> Update macro-libraries (shapeless and magnolia)

docs/macros/macro-libraries.md
A boilerplate-free way to make React components, not working in Scala3
=> Add payalabs/scalajs-react-bridge

docs/macros/macro-libraries.md
Mill API can be used as library, e.g. to develop Mill plugins. Macros are used to rewrite `def`s for tasks into applicatives.
=> Added mill to library list

docs/macros/macro-libraries.md
This pull request adds [ScalikeJDBC](https://github.com/scalikejdbc/scalikejdbc) to the list of Scala 3 ready ones.
Refer to https://github.com/scalikejdbc/scalikejdbc/releases/tag/4.0.0 for the details of its v4 release.
=> Add ScalikeJDBC to Scala 3 ready macro libraries
